my_var: ENC[AES256_GCM,data:KChDpmaFPBCEpVPPsSqKaTHy,iv:bokBTJNo68zPwzsxJGj3sqVeHKVerUpP4qwS8QF+W/0=,tag:xqzARkJgMBNcY1SqhMl8Qg==,type:str]
my_other_var: ENC[AES256_GCM,data:LP3aG8vups0j+pFPfAngg/Jw8+wOpHFprL4BOnCQGMsnUu+zPGvVtY2RPJnctNVMj5aq4ZqEHA==,iv:sNgeAx+jBliVgScIHyRC2ZgYCTMF8ZOB1AUGVlhxOoU=,tag:ZWmtqFm19O4PrDZLmgwwPA==,type:str]
sops:
    kms:
        - arn: arn:of:your:kms:key
          created_at: "2023-05-05T10:05:37Z"
          enc: AQICAHjzPvzVhXFf2O2F8UpFSQNI9j8TECONXE4LKKsFpGYytQF4HDVQ93uzmojc0SXILd9vAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMli+9R7l3UyRtRyA1AgEQgDvPoze4FIsBPOyF099Wr2f+DCBImib2G/K7qjXAEtUPFRsBgs3cEtWAquFeT6k3JGeGw8RaRZgZs7FSyA==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-05-05T12:58:03Z"
    mac: ENC[AES256_GCM,data:z/bmf+B8BnmsborrVvKR47qa5ODFNMBC4AzyleFh+4bDjD+B7lEZmVG7PNbl+mP42spDz9S6J2CulUtC25NZOkHbw7KEkLC3sEQet6wAIm35u/WwHDevXgpRHsW4dh0G8jq3+XfZdRXU2R41I2CxuCW7PeIdiwdvPv9T5borVnY=,iv:4mEK9icAC4ZXyZoz980tO1TEO2WpbEfHpFpyMSBGTH0=,tag:kQ3SwUDlav1seqMKHSHnfQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
